# @Author: guiguan
# @Date:   2017-05-16T00:15:57+10:00
# @Last modified by:   wahaj
# @Last modified time: 2017-07-21T09:56:32+10:00

pipeline:
  cienvy:
    image: southbanksoftware/cienvy:node-nm-mongo
    pull: true
    volumes:
      - /home/core/cienvy-client:/cienvy-client
      - cienvy-volumes:/volumes
    secrets: [SSH_PRIVATE_KEY]
    commands:
      - bash /cienvy-client/bin/cienvy.bash --url=http://172.16.0.1:9090 prepare core
  slack_legacy:
    image: plugins/slack
    pull: true
    volumes:
      - cienvy-volumes:/volumes
    secrets: [SLACK_WEBHOOK]
    webhook: ${SLACK_WEBHOOK}
    channel: ci
    template: >
      Build <{{build.link}}|{{build.number}}> (<https://github.com/{{repo.owner}}/{{repo.name}}/commit/{{build.commit}}|{{truncate build.commit 8}}>) of <https://github.com/{{repo.owner}}/{{repo.name}}|{{repo.owner}}/{{repo.name}}> has {{#success build.status}}succeeded{{else}}failed{{/success}} in {{since job.started}}
      <@{{build.author}}>: {{{build.message}}}
    when:
      status: [success, failure]

branches: master
