# @Author: Guan Gui <guiguan>
# @Date:   2016-06-02T14:58:00+10:00
# @Email:  root@guiguan.net
# @Last modified by:   guiguan
# @Last modified time: 2017-05-23T02:20:36+10:00

extends: airbnb
parser: babel-eslint
env:
  browser: true
  node: true
  jest: true
  es6: true
rules:
  arrow-body-style: 0
  key-spacing: 0
  object-property-newline: 0
  no-cond-assign: [error, except-parens]
  no-nested-ternary: 0
  no-shadow: 0
  eqeqeq: 0
  array-callback-return: 0
  no-param-reassign: 0
  space-before-function-paren: 0
  global-require: 0
  consistent-return: 0
  quote-props: 0
  no-underscore-dangle: 0
  prefer-const: [error, {ignoreReadBeforeAssign: true}]
  max-len: 0
  prefer-template: 0
  object-curly-spacing: 0
  comma-dangle: 0
  indent: 0
  no-console: 0
  no-alert: 0
  no-multiple-empty-lines: [2, {max: 3}]
  func-names: 0
  new-cap: [2, {capIsNew: false}]
  import/default: 0
  import/no-duplicates: 0
  import/named: 0
  import/namespace: 0
  import/no-named-as-default: 2
  # this requires eslint-import-resolver-node@0.3.0 to be installed in order for import/resolver settings to work
  import/no-unresolved: [2, {ignore: ["^[~]", "^[#]"]}]
  import/prefer-default-export: 0
  import/no-extraneous-dependencies: 0
  import/extensions: 0
  react/prefer-stateless-function: 0
  react/jsx-space-before-closing: 0
  react/jsx-first-prop-new-line: 0
  linebreak-style: 0
  react/jsx-closing-bracket-location: 0
  react/no-multi-comp: 0
  react/no-did-mount-set-state: 0
  no-unused-vars: [error, {argsIgnorePattern: ^_}]
  no-restricted-syntax: 0
  no-unused-expressions: 0
  newline-per-chained-call: 0
  no-use-before-define: [error, {functions: false, classes: true}]
plugins: [react, import]
settings:
  import/resolver:
    node:
      moduleDirectory:
        - node_modules
        - src
globals:
  l: false
  MODE: false
